language: php

php:
- 5.6

sudo: false

services:
  - redis-server
  - memcached

before_script:
- composer self-update
- composer install --prefer-dist --no-interaction
- mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc
- echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
 - composer require satooshi/php-coveralls:~0.6@stable

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'

